baseURL = "https://vaishnavi171.github.io/mlnotes/"
languageCode = "en-us"
title = "Vaishnavi"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
